### ISSUE TITLE
Feature - easily import speakers & talk information into the repo

### ISSUE THREAD

**Issue by crtr0** [seattlejs/seattlejs.com#98]
## Problem

When prospective speakers submit to our CFP, their information is stored in Airtable. It is very time consuming to port information for accepted speakers into our repo, where we store information in JSON files for speakers, talks and events.

## Possible Solution

A CLI tool that:
- lists upcoming events (based on Airtable)
- allow the user to select an event
- imports event/speakers/talks based on the following rules
  - creates a new entry in `events.json` ONLY IF the event doesn't already exist
  - creates a new entry in `speakers.json` ONLY IF the speaker doesn't already exist
  - creates a new image in `public/images/speakers` for the new speaker ONLY IF the speaker doesn't already exist
  - creates a new entry in `talks.json` ONLY IF the talk doesn't already exist

The way we will identify speakers is this:
- Take the full name that is submitted, trim the white space from the front and back, lowercase, and substitute space for `-` in order to create an `id` (use https://www.npmjs.com/package/slugify)
- For better or worse, we will hope this `id` is unique among our speakers

**Comment by andrewiggins** [comment]
For speakers and their images, should add or update the entry? If we have a speaker speak twice and they upload a new image of themselves, should we update it?

**Comment by crtr0** [comment]
FX and I discussed this and opted to keep the current entry as the default. If we know a photo (or other attribute) is new, we can handle that manually. But the default should not be to overwrite.

**Comment by FX-Wood** [comment]
Notes from the demo:

idea to make a ci version of it:
- don't save credentials
- read credentials from env var
- check ci variable (this is a GitHub actions thing)
- consider making an action in the seattlejs.com repo:
    - make branch
    - `npx seattlejs-airtable-cli`
    - open PR
    - human reviews/rescales photos (I will try to automate this)
